include:
  - proxy.yaml

x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M
x-env_file: &env_file
  env_file:
    - .env
x-restart: &restart
  restart: on-failure

services:
  db:
    image: mysql:8
    networks:
      backend:
        ipv4_address: 172.20.0.10
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%" # it's very important!!!
    healthcheck:
      test: ["CMD-SHELL", "mysql -uroot -p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  
  web:
    depends_on:
      db:
        condition: service_healthy
        restart: true
    image: web:latest
    build:
      context: .
      dockerfile: Dockerfile.python
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - "127.0.0.1:5000:8000"
    extra_hosts:
    - "db=172.20.0.10"
    volumes:
    - web_data:/var/www/html
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - DB_HOST=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      
volumes:
  db_data: {}
  web_data: {}